hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${env.root_dir}/output/${exp_name}/single
  sweep:
    dir: ${env.root_dir}/output/${exp_name}
    subdir: run${hydra.job.num}
  callbacks:
    save_job_info:
      _target_: hydra.experimental.callbacks.PickleJobInfoCallback

defaults:
  - _self_
  - env: server
  - dataset: rating_dataset
  - model: mf
  - optimizer: adam
  - scheduler: constant
  - callbacks:
    - early_stopping
    - model_checkpoint
    - learning_rate_monitor
    - model_summary
    - swa
    - timer
  - metrics:
    - regression

# 評価指標の中で第一優先の指標を指定
monitor: mse
mode: min
# 辞書型のバッチデータのkey名を指定
INDEX_ID: ~
LABEL_ID: label
PRED_ID: logits
# プログラム結果を識別するための情報
project_name: ~
exp_name: dummy
stage: train
output_dir: ~
seed: 42
# データに関する情報
data_dir: ${env.root_dir}/data
dataset_name: debug
folds: [0]
batch_size: 2048
num_workers: 1
# Trainerのパラメータ
# https://lightning.ai/docs/pytorch/stable/common/trainer.html#trainer-class-api
trainer:
  max_epochs: 100
  min_epochs: 10
  devices: [0]
  precision: "16-mixed"
  accumulate_grad_batches: 1
  gradient_clip_val: ~
  gradient_clip_algorithm: norm
  accelerator: auto
  strategy: auto
  num_nodes: 1
  enable_progress_bar: True
  val_check_interval: 1.0
  log_every_n_steps: 50
  deterministic: False
  benchmark: False
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: True
